[package]
name = "drop"
version = "0.3.2"
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
num-format = "0.4.0"
prettytable-rs = "0.8.0"
rand = "0.8.4"

[profile.release]
codegen-units = 1
lto = true
opt-level = 's'
panic = 'abort'